### ISSUE TITLE
retrieveNWISqwdata parameter selection

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/dataRetrieval#57] opened 2014-12-11 17:24 UTC
Add in NWIS parameters groups as selection options for pCodes. At a minimum, allow for pull of all measured pCodes at a site.

**Comment by ldecicco-USGS** [comment] 2015-01-02 21:28
I'll look into using this:
http://nwis.waterdata.usgs.gov/usa/nwis/qwdata
more effectively. 
I'm grabbing all the other data from waterservices (not waterdata), so I haven't had to pay as much attention to this url generation scheme.

**Comment by ldecicco-USGS** [comment] 2015-01-22 17:04
@dlorenz-usgs has the same request. Need to bump up priority.

**Comment by ldecicco-USGS** [comment] 2015-01-29 15:23
I need to submit an update to CRAN (NWISweb slightly changed their server config). I will get the param="all" update in this next release, but not parameter groups...that will be a future release.

**Comment by ldecicco-USGS** [comment] 2015-02-18 19:00
I added the parameter_group option. Choosing one group seems fine. Choosing more than one, I'm still troubleshooting if it's correct or not. Fewer rows are returned (but the number of parameter codes is greater). I assume that is because choosing the 2 groups means NWIS will return the sites that have both groups (AND instead of OR). 

I'll keep troubleshooting, but if anyone just knows the answer, feel free to let me know (@tmills-usgs, @dlorenz-usgs ?).

Here are 3 example urls:
Nutrient:
http://nwis.waterdata.usgs.gov/nwis/qwdata?multiple_site_no=04024430,04024000&sort_key=site_no&group_key=NONE&inventory_output=0&begin_date=2010-01-01&end_date=&TZoutput=0&param_group=NUT&qw_attributes=0&format=rdb&qw_sample_wide=0&rdb_qw_attributes=expanded&date_format=YYYY-MM-DD&rdb_compression=value&list_of_search_criteria=multiple_site_no
(returns 1512 rows)

Organics:
http://nwis.waterdata.usgs.gov/nwis/qwdata?multiple_site_no=04024430,04024000&sort_key=site_no&group_key=NONE&inventory_output=0&begin_date=2010-01-01&end_date=&TZoutput=0&param_group=OPE&qw_attributes=0&format=rdb&qw_sample_wide=0&rdb_qw_attributes=expanded&date_format=YYYY-MM-DD&rdb_compression=value&list_of_search_criteria=multiple_site_no
(returns 585 rows)

Both:
http://nwis.waterdata.usgs.gov/nwis/qwdata?multiple_site_no=04024430,04024000&sort_key=site_no&group_key=NONE&inventory_output=0&begin_date=2010-01-01&end_date=&TZoutput=0&param_group=NUT,OPE&qw_attributes=0&format=rdb&qw_sample_wide=0&rdb_qw_attributes=expanded&date_format=YYYY-MM-DD&rdb_compression=value&list_of_search_criteria=multiple_site_no
(returns 837 rows)

If I try to reproduce with the point and click browser option, I get no results...but I've never been very successful at navigating that site:

http://nwis.waterdata.usgs.gov/nwis/qwdata?multiple_site_no=04024430%2C04024000&param_group=NUT&param_group=OPE&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&inventory_output=0&rdb_inventory_output=file&begin_date=2013-10-01&end_date=2014-09-30&TZoutput=inUTC&pm_cd_compare=Greater%20than&radio_parm_cds=previous_parm_cds&format=html_table&qw_attributes=expanded&qw_sample_wide=wide&rdb_qw_attributes=0&date_format=YYYY-MM-DD&rdb_compression=value&list_of_search_criteria=multiple_site_no%2Cparam_group

**Comment by ldecicco-USGS** [comment] 2015-02-18 22:34
OK, this is merged into the main branch. I'm confident that with one parameter group it's working right. I'm confident that `dataRetrieval` is returning the data correctly with 2 groups...I'm just not 100% sure what that data is.

If anyone knows, or knows who to ask, please let me know.

**Comment by ldecicco-USGS** [comment] 2015-02-19 22:26
Ah HA!
When you ask for more than one group, you only get sites back that have both (thanks to @eread-usgs ). I will document this, push it, and get it out to CRAN soon. The only lingering question I have is can I over-ride that behavior through the url, so I get all the data back?

**Closed** 2015-02-23 14:36 UTC
Labels: enhancement
